dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.1.0
  provider: ^6.0.0
  uuid: ^4.0.0
  shared_preferences: ^2.0.0
  flutter_slidable: ^3.0.0
  animations: ^3.0.0
